baseurl: ""
url: "https://anicka-old-site-def1620"
collections_dir: content

collections:
  services:
    output: true

# i18n
languages: ["sk", "en", "es"]
exclude_from_localizations: ["js", "images", "css"]

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-multiple-languages-plugin
